### ISSUE TITLE
Upload fails with datetime64[ns]

### ISSUE THREAD

**Issue by galexioza** [areisTaylorCorp/pd_to_mssql#1]
pd-to-mssql recently started failing on me and giving me the following error:

`There are more columns in the INSERT statement than values specified in the VALUES clause.` 

When I checked the debugging script I saw that the date values were missing from the insert statement. After some testing, I found that if I convert dates to strings first, the upload is successful.

I believe the issue comes down to this if statement, which never considers the type datetime64[ns]:

https://github.com/veyron8800/pd_to_mssql/blob/0b0f03103ceaadee6fc5576b2bb5afc5eb47e559/pd_to_mssql/pd_to_mssql.py#L62

**Comment by veyron8800** [comment]
Hello @galexioza 

The type names listed on that if statement are for the tsql data types, not the python ones. I'm confused by the fact that your solution works, as all columns are stringified before the upload, so converting it explicitly before calling to_sql shouldn't change anything. Could you verify that the data type of the column in the table you are uploading to is _datetime2_. If it is the old _datetime_ then that could be causing this issue, as the package does not support it.

If that is not the issue, then I would need some more info to figure out the problem. If you could share code and example data, that would be great. If the data and code in question are sensitive in nature, then a minimum example with fake data would be much appreciated.

Thanks

**Comment by galexioza** [comment]
Since pd-to-mssql can't create tables, I am using pandas to_sql method first to create the table with one row, then truncating it, then uploading the rest with pd-to-mssql. 

Converting to a string works because it sets the column on the server to varchar. So that isn't really what I want.

The datatype is 'datetime', which must be the default set by pandas. Any idea if there is a way to specify this type in pandas? If not, then I will just create the table first with a text SQL statement.

**Comment by galexioza** [comment]
Manually creating a table with datetime2 instead of relying on pandas worked, so I'll close the issue as it's my problem to work around.

Thanks for your help and surprisingly quick response.

**Comment by veyron8800** [comment]
Hello @galexioza 

The documentation for Pandas' [to_sql function](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html) suggests that it is possible for you to specify the datatypes of the columns in the resulting sql table through the dtype parameter. However, when I use this package, I always just create the table using a tsql statement like you did with your workaround.

Thank you for using the package!
